-- Owner: Tijil. A MADE-UP matter in the same shape Clio returns, for running the pipeline
-- and both portals without a Clio account. Load: docker compose exec -T db psql -U casebrief < tests/pipeline/seed.sql
DELETE FROM raw_records WHERE matter_id = 9001 OR (resource = 'contacts' AND clio_id BETWEEN 9100 AND 9199);
INSERT INTO raw_records (resource, clio_id, matter_id, etag, record_date, data) VALUES
('matters', 9001, 9001, 'm1', '2025-02-03', '{"id":9001,"description":"Okafor, Dana - rear-end collision","status":"Open","client":{"id":9101,"name":"Dana Okafor"},"matter_stage":{"id":1,"name":"Treatment"},"statute_of_limitations":{"id":9301,"due_at":"2027-01-20","status":"pending"},"custom_field_values":[{"id":"date-1","field_name":"Date of Incident","field_type":"date","value":"2025-01-20"},{"id":"currency-2","field_name":"Estimated Case Value","field_type":"currency","value":"180000"},{"id":"text_area-3","field_name":"Policy Limits","field_type":"text_area","value":"Defendant liability: $100,000 per person"}]}'),
('contacts', 9101, NULL, 'c1', NULL, '{"id":9101,"name":"Dana Okafor","type":"Person","primary_email_address":"dana@mailbox.test"}'),
('contacts', 9102, NULL, 'c2', NULL, '{"id":9102,"name":"Lakeside Physical Therapy","type":"Company","primary_email_address":"records@lakesidept.test"}'),
('contacts', 9103, NULL, 'c3', NULL, '{"id":9103,"name":"Granite Mutual Insurance","type":"Company","primary_email_address":"claims@granitemutual.test"}'),
('relationships', 9201, 9001, 'r1', NULL, '{"id":9201,"description":"Treating provider, physical therapy","contact":{"id":9102,"name":"Lakeside Physical Therapy"}}'),
('relationships', 9202, 9001, 'r2', NULL, '{"id":9202,"description":"Insurance carrier for the defendant","contact":{"id":9103,"name":"Granite Mutual Insurance"}}'),
('notes', 9401, 9001, 'n1', '2025-02-03', '{"id":9401,"subject":"Intake summary","detail":"Client was stopped at a light when a delivery van struck her from behind. The adjuster says the van carries a $250,000 policy. Client says she has dashcam footage and will send it. Left shoulder procedure performed at DOI + 40."}'),
('notes', 9402, 9001, 'n2', '2025-06-10', '{"id":9402,"subject":"Coverage letter received","detail":"Carrier letter states a bodily injury limit of $100,000 per person. Two requests for the therapy file have gone unanswered. Medical lien asserted at $8,500. Nobody has asked the client for the dashcam footage."}'),
('communications', 9501, 9001, 'e1', '2025-03-01', '{"id":9501,"subject":"Records request: physical therapy file","body":"Please provide the complete physical therapy file including itemised billing.","type":"EmailCommunication","senders":[{"id":1,"name":"Firm User","type":"User"}],"receivers":[{"id":9102,"name":"Lakeside Physical Therapy","type":"Contact"}]}'),
('communications', 9502, 9001, 'e2', '2025-04-15', '{"id":9502,"subject":"Second request: physical therapy file","body":"We have not received the file requested earlier. Please advise.","type":"EmailCommunication","senders":[{"id":1,"name":"Firm User","type":"User"}],"receivers":[{"id":9102,"name":"Lakeside Physical Therapy","type":"Contact"}]}'),
('communications', 9503, 9001, 'e3', '2025-05-20', '{"id":9503,"subject":"Third request: physical therapy file","body":"Third request for the therapy file and ledger.","type":"EmailCommunication","senders":[{"id":1,"name":"Firm User","type":"User"}],"receivers":[{"id":9102,"name":"Lakeside Physical Therapy","type":"Contact"}]}'),
('communications', 9504, 9001, 'e4', '2025-07-02', '{"id":9504,"subject":"Call with client","body":"Client still attending therapy weekly. Will send the dashcam footage this week.","type":"PhoneCommunication","senders":[{"id":1,"name":"Firm User","type":"User"}],"receivers":[{"id":9101,"name":"Dana Okafor","type":"Contact"}]}'),
('tasks', 9301, 9001, 't1', '2027-01-20', '{"id":9301,"name":"Limitations Date","status":"pending","description":"Statute of limitations.","assignee":{"id":1,"name":"Firm User"}}'),
('tasks', 9302, 9001, 't2', '2025-05-01', '{"id":9302,"name":"By medical provider: Lakeside Physical Therapy - updated ledger","status":"pending","description":"Itemised ledger needed.","assignee":{"id":1,"name":"Firm User"}}'),
('calendar_entries', 9601, 9001, 'k1', '2025-03-01', '{"id":9601,"summary":"Left shoulder procedure","description":"Outpatient procedure.","start_at":"2025-03-01T09:00:00Z"}'),
('activities', 9701, 9001, 'a1', '2025-03-20', '{"id":9701,"type":"ExpenseEntry","note":"Records reproduction: therapy file copy fee.","total":45,"price":45}'),
('documents', 9801, 9001, 'd1', '2025-02-03', '{"id":9801,"name":"photo-id.pdf","parent":{"id":1,"name":"01 Intake"}}');
